export const ERROR_MESSAGES = {
  400: 'Invalid request. Please try again.',
  401: 'Please log in to continue.',
  403: 'Access denied.',
  404: 'The content does not exist.',
  408: 'Request took too long. Try again.',
  422: 'Invalid input. Please try again.',
  500: 'Oops! Something went wrong. Try later.',
  502: 'Connection issue. Try later.',
  503: 'Service is down. Try later.',
  504: 'Server took too long. Try again.',
  common: 'Oops! Something went wrong. Try later.',
};

export const INCOME_CATEGORIES = [
  "Salary",
  "Business",
  "Investments",
  "Freelancing",
  "Interest",
  "Rental Income",
  "Bonus",
  "Commission",
  "Side Hustle",
  "Other Income",
];

export const EXPENSE_CATEGORIES = [
  "Food & Dining",
  "Groceries",
  "Shopping",
  "Travel",
  "Health",
  "Medicine",
  "Education",
  "Bills & Utilities",
  "Rent",
  "Insurance",
  "Loan EMI",
  "Entertainment",
  "Fuel",
  "Subscriptions",
  "Personal Care",
  "Maintenance",
  "Gifts & Donations",
  "Taxes",
  "Other Expense",
];